grps/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = 'grps'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='groups'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

mssgs/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views
# from .views import MessageWizard

app_name = 'mssgs'
urlpatterns = [
    url(r'^message$', views.MessageView.as_view(), name='message'),
    # url(r'^messages$', views.IndexView.as_view(), name='messages'),
    url(r'^messages$', views.MessageList.as_view(), name='messages'),
    url(r'^user_info$', views.user_info, name='user_info'),
    url(r'^msg/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^new_message$', MessageWizard.as_view(MessageWizard.form_list),
    # name='new_message'),
    url(r'^(?P<group>[0-9]+)/new_message$',
        views.MessageView.as_view(),
        name='new_message'),
    url(r'^webcam_upload$', views.webcam_upload, name='webcam_upload'),
]

ruik/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^mssgs/', include('mssgs.urls')),
    url(r'^groups/', include('grps.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^.*', include('grps.urls')),
]

templates/ruik/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>{% block head_title %}АИС «РУИК»{% endblock %}</title>
  <!-- Bootstrap -->

  {% bootstrap_css %}
  {% bootstrap_messages %}
  <link href="{% static "bootstrap-table/bootstrap-table.css" %}" rel="stylesheet">
  {% include 'ruik/head_css.html' %}

</head>
<body>
  {% include 'ruik/navbar.html' %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  {% bootstrap_javascript %}
  <script src="{% bootstrap_jquery_url %}"></script>
  <script src="{% static "bootstrap-table/bootstrap-table.js" %}"></script>
  <script src="{% static "bootstrap-table/locale/bootstrap-table-ru-RU.js" %}"></script>
  <script src="{% static "js/thumbnail.js" %}"></script>

<div class="container navbar-fixed-bottom">
<div class="row">
<div class="well well-sm">
<small>
Приложение: {{ request.resolver_match.app_names }}<br />
URL-пространство: {{ request.resolver_match.namespaces }}<br />
URL-переменная: {{ request.resolver_match.url_name }}<br />
request: {{ request.resolver_match }}<br />
Пользователь: {{ request.user }}<br />
</small>
</div>
</div>
</div>
</body>
</html>

templates/ruik/head_css.html
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<style>
  .nonactive_group {
    display:none;
  }
  .nonactive_group div {
    background-color: lightgrey;
  }
</style>

<style>
.material-switch > input[type="checkbox"] {
    display: none;
}

.material-switch > label {
    cursor: pointer;
    height: 0px;
    position: relative;
    width: 40px;
}

.material-switch > label::before {
    background: rgb(0, 0, 0);
    box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.5);
    border-radius: 8px;
    content: '';
    height: 16px;
    margin-top: 0px;
    position:absolute;
    opacity: 0.3;
    transition: all 0.4s ease-in-out;
    width: 40px;
}
.material-switch > label::after {
    background: rgb(255, 255, 255);
    border-radius: 16px;
    box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
    content: '';
    height: 24px;
    left: -4px;
    margin-top: 0px;
    position: absolute;
    top: -4px;
    transition: all 0.3s ease-in-out;
    width: 24px;
}
.material-switch > input[type="checkbox"]:checked + label::before {
    background: inherit;
    opacity: 0.5;
}
.material-switch > input[type="checkbox"]:checked + label::after {
    background: inherit;
    left: 20px;
}

.navbar .divider-vertical {
height: 40px;
margin-top: 5px;
border-left: 1px solid silver;
border-right: 1px solid #ffffff;
/*border-right: 1px solid red;*/
}


</style>

templates/ruik/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">АИС «РУИК»</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li {% if request.resolver_match.url_name == 'messages' %}class="active"{% endif %}><a href="{% url 'mssgs:messages' %}">Все замечания</a></li>
        <!-- <li><a href="{% url 'mssgs:message' %}">Новое замечание</a></li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Объекты<span class="caret"></span></a>
        <ul class="dropdown-menu">
        <li><a href="{% url 'grps:groups' %}">Все группы</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="#">Separated link</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="#">One more separated link</a></li>
      </ul>
    </li> -->
    {% if request.resolver_match.url_name == 'groups' %}<li class="divider-vertical"></li>{% endif %}
  </ul>


{% if request.resolver_match.url_name == 'groups' %}
  <div class="navbar-form nav navbar-nav navbar-left">
    <div class="material-switch pull-right" title="Показать все группы">
      <input  id="someSwitchOptionDefault" name="someSwitchOption001" type="checkbox" class="check_thumbs" />
      <label for="someSwitchOptionDefault" class="label-default"></label>
    </div>
  </div>
{% endif %}

  <!-- <form class="navbar-form navbar-left">
  <div class="form-group">
  <input type="text" class="form-control" placeholder="Search">
</div>
<button type="submit" class="btn btn-default">Submit</button>
</form> -->
<ul class="nav navbar-nav navbar-right">
  <li><a href="#">{{ user.username }}</a></li>
  <!-- <li><a href="#">Link</a></li>
  <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
  <ul class="dropdown-menu">
  <li><a href="#">Action</a></li>
  <li><a href="#">Another action</a></li>
  <li><a href="#">Something else here</a></li>
  <li role="separator" class="divider"></li>
  <li><a href="#">Separated link</a></li>
</ul>
</li> -->
</ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>