grps/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = 'grps'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='groups'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

mssgs/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views
# from .views import MessageWizard

app_name = 'mssgs'
urlpatterns = [
    url(r'^message$', views.MessageView.as_view(), name='message'),
    # url(r'^messages$', views.IndexView.as_view(), name='messages'),
    url(r'^messages$', views.MessageList.as_view(), name='messages'),
    url(r'^user_info$', views.user_info, name='user_info'),
    url(r'^msg/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^new_message$', MessageWizard.as_view(MessageWizard.form_list),
    # name='new_message'),
    url(r'^(?P<group>[0-9]+)/new_message$',
        views.MessageView.as_view(),
        name='new_message'),
    url(r'^webcam_upload$', views.webcam_upload, name='webcam_upload'),
]

mssgs/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey

def upload_location(instance, filename):
    return "{}/{}".format(datetime.now().strftime("%Y-%m"), filename)

class CategoriesSet(models.Model):
    categories_set_name = models.CharField(max_length=250, verbose_name='Набор категорий')

    def __str__(self):
        return self.categories_set_name

    class Meta:
        ordering = ['categories_set_name']
        verbose_name = 'Набор категорий'
        verbose_name_plural = 'Наборы категорий'

class Category(MPTTModel):
    category        = models.CharField(max_length=250, verbose_name='Категория')
    parent          = TreeForeignKey('self',  null=True, blank=True, verbose_name='Родительская категория', related_name='children', db_index=True)
    category_set    = models.ForeignKey(CategoriesSet,  null=True, blank=True, verbose_name='Набор категорий', related_name='categories')

    def __str__(self):
        return self.category

    class Meta:
        ordering = ['category']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    class MPPTMeta:
        order_insertion_by = ['category']

class Message(models.Model):
    group           = models.ForeignKey('grps.Group', verbose_name='Группа', default='', blank=False, related_name='messages')
    category        = models.ForeignKey(Category, verbose_name='Категория', blank=False, related_name='messages')
    message_text    = models.TextField('Замечание', blank=False, null=False)
    date_create     = models.DateTimeField('Дата создания', auto_now_add=True)
    date_updated    = models.DateTimeField('Дата редактирования', auto_now=True)
    photo           = models.ImageField(upload_to=upload_location, null=True, blank=True)
    author          = models.CharField('Пользователь', max_length=250, null=False, blank=False)

    def __str__(self):
        return '{}'.format(self.message_text)

    class Meta:
        ordering = ['-date_create']
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class MessageImageAttachment(models.Model):
    message     = models.ForeignKey(Message, verbose_name='Замечание', related_name='images')
    image_file  = models.ImageField('ImageAttachment', upload_to=upload_location, null=True, blank=True)


class StatusLog(models.Model):
    message     = models.ForeignKey(Message, verbose_name='Сообщение', blank=False, related_name='status_logs')
    date_create = models.DateTimeField('Дата создания', auto_now_add=True)
    status = models.CharField('Статус задачи', max_length=100, null=False, blank=False, unique=True)
    initiator = models.ForeignKey(User, verbose_name='Пользователь', related_name='status_logs_initiators')

mssgs/forms.py
from django import forms
from django.forms import ModelForm, HiddenInput, TextInput
from multiupload.fields import MultiImageField
from django.forms.widgets import RadioSelect, FileInput, Select, CheckboxInput

from .models import Message, MessageImageAttachment, Category
from grps.models import Group
from mptt.forms import TreeNodeChoiceField

class MessageForm(ModelForm):

    def __init__(self, *args, **kwargs):
        group_id = kwargs['initial']['group']
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields['images'].required = False
        category = TreeNodeChoiceField(Category.objects.filter(category_set=Group.objects.get(id=group_id).category_set), level_indicator=u'→')
        self.fields['category'] = category
        self.fields['category'].empty_label = 'Категория...'
        self.fields['category'].label = 'Категория'

    class Meta:
        model = Message
        fields = ['group', 'category', 'message_text']
        widgets = {
            'group': HiddenInput(),
        }

    images = MultiImageField(min_num=1, max_num=3,
                             max_file_size=1024 * 1024 * 10)


    def save(self, commit=True):
        # if Category.objects.filter(parent=self.cleaned_data['category']):
        #     raise Exception('parent')
        # else:
        #     raise Exception('child')
        instance = super(MessageForm, self).save(commit)
        for each in self.cleaned_data['images']:
            MessageImageAttachment.objects.create(
                image_file=each, message=instance)
        return instance

#
# class MessageFormGroup(ModelForm):
#     class Meta:
#         model = Message
#         fields = ['group']
#         widgets = {
#             'group': RadioSelect,
#         }


# class MessageFormCategory(ModelForm):
#     class Meta:
#         model = Message
#         fields = ['category']


# class MessageFormText(ModelForm):
#     class Meta:
#         model = Message
#         fields = ['message_text']

    # images = MultiImageField(min_num=1, max_num=3, max_file_size=1024*1024*10)
    #
    # def save(self, commit=True):
    #     instance = super(MessageForm, self).save(commit)
    #     for each in self.cleaned_data['images']:
    #         MessageImageAttachment.objects.create(image_file=each, message=instance)
    #     return instance

mssgs/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.views import generic
from django.contrib import messages
from django.views.generic.edit import FormView, CreateView
# from django.core.mail import send_mail
from django_tables2 import RequestConfig
from formtools.wizard.views import SessionWizardView
from django.core.files.storage import FileSystemStorage
from datetime import datetime
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView

from django.http import JsonResponse

import os
import logging

logger = logging.getLogger(__name__)

from .tables import MessageTable
from .models import Message, Category
from grps.models import Group
from .forms import MessageForm

from django.forms.widgets import TextInput

def upload_location(instance, filename):
    return "{}/{}".format(datetime.now().strftime("%Y-%m"), filename)


# def index(request):
#     table = MessageTable(Message.objects.all())
#     RequestConfig(request, paginate={'per_page': 50}).configure(table)
#     return render(request, 'mssgs/messages_table.html', {'table': table})

class MessageList(ListView):
    model = Message
    context_object_name = 'message_list'

@csrf_exempt
def webcam_upload(request):
    if request.POST:
        f = open(settings.MEDIA_ROOT + '/webcamimages/someimage.jpg', 'wb')
        f.write(request.raw_post_data)
        f.close()
        return HttpResponse('http://localhost:8080/site_media/webcamimages/someimage.jpg')
    else:
        logger.info('iSomething went wrong!')
        logger.warning('wSomething went wrong!')
        logger.debug('dSomething went wrong!')
        logger.error('eSomething went wrong! {}'.format(request.POST))
        return HttpResponse('no data')


def user_info(request):
    user_info = request.META['REMOTE_USER']
    #user_info = request.environ.get('REMOTE_USER')
    return render(request, 'mssgs/user_info.html', {'user_info': user_info})


class DetailView(generic.DetailView):
    model = Message


class MessageView(CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'mssgs/message_form.html'
    success_url = 'messages'

    def get_context_data(self, **kwargs):
        group_id = self.kwargs['group']
        context = super(MessageView, self).get_context_data(**kwargs)
        context['group'] = Group.objects.get(pk=group_id)
        return context

    def get_initial(self):
        initial = super(MessageView, self).get_initial()
        group_id = self.kwargs['group']
        group = Group.objects.get(pk=group_id)
        initial['group'] = group.id
        return initial

    # def get_form(self, form_class):
    #     group_id = self.kwargs['group']
    #     form = super(MessageView, self).get_form(form_class)
    #
    #     form.fields['category'] = Category.objects.filter(category_set=Group.objects.get(id=group_id).category_set)
    #     return form

# class MessageWizard(SessionWizardView):
#     form_list = [MessageFormGroup, MessageFormCategory, MessageFormText]
#
#     def get_template_names(self):
#         return ['mssgs/message_form_step.html']
#     # file_storage = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'temp'))
#
#     def done(self, form_list, **kwargs):
#         pass
#         return HttpResponseRedirect('')

def change_message_status(request):
    # username = request.GET.get('username', None)
    status = 'В работе'
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)

mssgs/templates/mssgs/_message_list.html
{% extends "ruik/base.html" %}
{% load render_table from django_tables2 %}
{% load static %}


{% block head_title %}Списки | {{ block.super }} {% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
{% if latest_message_list %}
    <ul>
    {% for message in latest_message_list %}
        <li><a href="{% url 'mssgs:detail' message.id %}">{{ message.message_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Нет сообщений.</p>
{% endif %}

{% render_table latest_message_list %}

{% endblock %}

mssgs/templates/mssgs/message_detail.html
{% extends "ruik/base.html" %}
{% block head_title %} Детали | {{ block.super }} {% endblock %}
{% block content %}

<h1>{{ message.message_text }}</h1>
<p>
Объект: <a href="{% url 'grps:detail' message.group.id %}">{{ message.group.group_name }}</a>
</p>
<p>
  <li>Время создания: {{ message.date_create }}</li>
  <li>Время изменения: {{ message.date_updated }}</li>
</p>
{% if message.images %}
  <p>
    <div class="row">
      {% for img in message.images.all %}
      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src='../../media/{{img.image_file}}' class='img-responsive' />
        </a>
      </div>
      {% endfor %}
    </div>
  </p>
{% endif %}
{% endblock %}

mssgs/templates/mssgs/message_form.html
{% extends "ruik/base.html" %}
{% block head_title %} Обращение | {{ block.super }} {% endblock %}

{% block content %}
{% load static %}

<form enctype="multipart/form-data" action="" method="post">
  <div class="page-header"><h3>{{ group }}</h3></div>
  {% csrf_token %}
  {% load bootstrap3 %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">
    {% bootstrap_icon "star" %} Отправить
  </button>
  {% endbuttons %}
</form>

{% endblock %}

mssgs/templates/mssgs/message_form0.html
{% extends "ruik/base.html" %}
{% block head_title %} Замечание | {{ block.super }} {% endblock %}

{% block content %}
{% load static %}

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Сделать снимок</h4>
      </div>
      <div class="modal-body">
        <DIV id="webcam"></DIV>
        <A href="javascript:webcam.capture();changeFilter();void(0);">Сделать снимок</A>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<form enctype="multipart/form-data" action="" method="post">
  {% csrf_token %}
  {% load bootstrap3 %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
  {% bootstrap_icon "camera" %}
  </button>
  <button type="submit" class="btn btn-primary">
    {% bootstrap_icon "star" %} Отправить
  </button>
  {% endbuttons %}
</form>



<CANVAS width="320" height="240" id="canvas"></CANVAS>



<SCRIPT src="{% static "mssgs/webcam_files/jquery-1.11.1.min.js" %}"></SCRIPT>

<SCRIPT src = "{% static "mssgs/webcam_files/jquery.webcam.min.js" %}" type="text/javascript"></SCRIPT>

<!-- <SCRIPT src = "{% static "mssgs/webcam_files/webcam.js" %}" type="text/javascript"></SCRIPT> -->
<SCRIPT type="text/javascript">
  var pos = 0;
  var ctx = null;
  var cam = null;
  var image = null;

  var filter_on = false;
  var filter_id = 0;

  function changeFilter() {
   if (filter_on) {
   filter_id = (filter_id + 1) & 7;
   }
  }

  function toggleFilter(obj) {
   if (filter_on =!filter_on) {
   obj.parentNode.style.borderColor = "#c00";
   } else {
   obj.parentNode.style.borderColor = "#333";
   }
  }

  jQuery("#webcam").webcam({

   width: 320,
   height: 240,
   mode: "callback",
   swffile: "{% static "mssgs/webcam_files/jscam_canvas_only.swf" %}",

   onTick: function(remain) {

   if (0 == remain) {
   jQuery("#status").text("Cheese!");
   } else {
   jQuery("#status").text(remain + " seconds remaining...");
   }
   },

   onSave: function(data) {

   var col = data.split(";");
   var img = image;

   if (false == filter_on) {

   for(var i = 0; i < 320; i++) {
   var tmp = parseInt(col[i]);
   img.data[pos + 0] = (tmp >> 16) & 0xff;
   img.data[pos + 1] = (tmp >> 8) & 0xff;
   img.data[pos + 2] = tmp & 0xff;
   img.data[pos + 3] = 0xff;
   pos+= 4;
   }

   } else {

   var id = filter_id;
   var r,g,b;
   var r1 = Math.floor(Math.random() * 255);
   var r2 = Math.floor(Math.random() * 255);
   var r3 = Math.floor(Math.random() * 255);

   for(var i = 0; i < 320; i++) {
   var tmp = parseInt(col[i]);

   /* Copied some xcolor methods here to be faster than calling all methods inside of xcolor and to not serve complete library with every req */

   if (id == 0) {
   r = (tmp >> 16) & 0xff;
   g = 0xff;
   b = 0xff;
   } else if (id == 1) {
   r = 0xff;
   g = (tmp >> 8) & 0xff;
   b = 0xff;
   } else if (id == 2) {
   r = 0xff;
   g = 0xff;
   b = tmp & 0xff;
   } else if (id == 3) {
   r = 0xff ^ ((tmp >> 16) & 0xff);
   g = 0xff ^ ((tmp >> 8) & 0xff);
   b = 0xff ^ (tmp & 0xff);
   } else if (id == 4) {

   r = (tmp >> 16) & 0xff;
   g = (tmp >> 8) & 0xff;
   b = tmp & 0xff;
   var v = Math.min(Math.floor(.35 + 13 * (r + g + b) / 60), 255);
   r = v;
   g = v;
   b = v;
   } else if (id == 5) {
   r = (tmp >> 16) & 0xff;
   g = (tmp >> 8) & 0xff;
   b = tmp & 0xff;
   if ((r+= 32) < 0) r = 0;
   if ((g+= 32) < 0) g = 0;
   if ((b+= 32) < 0) b = 0;
   } else if (id == 6) {
   r = (tmp >> 16) & 0xff;
   g = (tmp >> 8) & 0xff;
   b = tmp & 0xff;
   if ((r-= 32) < 0) r = 0;
   if ((g-= 32) < 0) g = 0;
   if ((b-= 32) < 0) b = 0;
   } else if (id == 7) {
   r = (tmp >> 16) & 0xff;
   g = (tmp >> 8) & 0xff;
   b = tmp & 0xff;
   r = Math.floor(r / 255 * r1);
   g = Math.floor(g / 255 * r2);
   b = Math.floor(b / 255 * r3);
   }

   img.data[pos + 0] = r;
   img.data[pos + 1] = g;
   img.data[pos + 2] = b;
   img.data[pos + 3] = 0xff;
   pos+= 4;
   }
   }

   if (pos >= 0x4B000) {
   ctx.putImageData(img, 0, 0);
   pos = 0;
   }
   },

   onCapture: function () {
   webcam.save();

   jQuery("#flash").css("display", "block");
   jQuery("#flash").fadeOut(100, function () {
   jQuery("#flash").css("opacity", 1);
   });
   },

   debug: function (type, string) {
   jQuery("#status").html(type + ": " + string);
   },

   onLoad: function () {

   var cams = webcam.getCameraList();
   for(var i in cams) {
   jQuery("#cams").append("<li>" + cams[i] + "</li>");
   }
   }
  });

  function getPageSize() {

   var xScroll, yScroll;

   if (window.innerHeight && window.scrollMaxY) {
   xScroll = window.innerWidth + window.scrollMaxX;
   yScroll = window.innerHeight + window.scrollMaxY;
   } else if (document.body.scrollHeight > document.body.offsetHeight){ // all but Explorer Mac
   xScroll = document.body.scrollWidth;
   yScroll = document.body.scrollHeight;
   } else { // Explorer Mac...would also work in Explorer 6 Strict, Mozilla and Safari
   xScroll = document.body.offsetWidth;
   yScroll = document.body.offsetHeight;
   }

   var windowWidth, windowHeight;

   if (self.innerHeight) { // all except Explorer
   if(document.documentElement.clientWidth){
   windowWidth = document.documentElement.clientWidth;
   } else {
   windowWidth = self.innerWidth;
   }
   windowHeight = self.innerHeight;
   } else if (document.documentElement && document.documentElement.clientHeight) { // Explorer 6 Strict Mode
   windowWidth = document.documentElement.clientWidth;
   windowHeight = document.documentElement.clientHeight;
   } else if (document.body) { // other Explorers
   windowWidth = document.body.clientWidth;
   windowHeight = document.body.clientHeight;
   }

   // for small pages with total height less then height of the viewport
   if(yScroll < windowHeight){
   pageHeight = windowHeight;
   } else {
   pageHeight = yScroll;
   }

   // for small pages with total width less then width of the viewport
   if(xScroll < windowWidth){
   pageWidth = xScroll;
   } else {
   pageWidth = windowWidth;
   }

   return [pageWidth, pageHeight];
  }

  window.addEventListener("load", function() {

   jQuery("body").append("<div id=\"flash\"></div>");

   var canvas = document.getElementById("canvas");

   if (canvas.getContext) {
   ctx = document.getElementById("canvas").getContext("2d");
   ctx.clearRect(0, 0, 320, 240);

   var img = new Image();
   img.src = "/image/logo.gif";
   img.onload = function() {
   ctx.drawImage(img, 129, 89);
   }
   image = ctx.getImageData(0, 0, 320, 240);
   }

   var pageSize = getPageSize();
   jQuery("#flash").css({ height: pageSize[1] + "px" });

  }, false);

  window.addEventListener("resize", function() {

   var pageSize = getPageSize();
   jQuery("#flash").css({ height: pageSize[1] + "px" });

  }, false);

</SCRIPT>


<SCRIPT src="{% static "mssgs/webcam_files/prettify.js" %}" type="text/javascript"></SCRIPT>

<SCRIPT src="{% static "mssgs/webcam_files/default.js" %}" type="text/javascript"></SCRIPT>
{% endblock %}

mssgs/templates/mssgs/message_form1.html
{% extends "ruik/base.html" %}
{% block head_title %} Обращение | {{ block.super }} {% endblock %}

{% block content %}
{% load static %}

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <form>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Сделать снимок</h4>
      </div>
      <div class="modal-body" align="center">
        <div id="webcam"></div>
        <div id="uploads"></div>
      </div>
      <div class="modal-footer">
        <input class="btn btn-default" type="button" value="Настроить..." onClick="webcam.configure()">
        <input class="btn btn-primary" type="button" value="Снять" onClick="webcam.snap()">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </form>
    </div>
  </div>
</div>


<form enctype="multipart/form-data" action="" method="post">
  {% csrf_token %}
  {% load bootstrap3 %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
  {% bootstrap_icon "camera" %}
  </button>
  <button type="submit" class="btn btn-primary">
    {% bootstrap_icon "star" %} Отправить
  </button>
  {% endbuttons %}



</form>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script type="text/javascript" src="{% static "mssgs/webcam.js" %}"></script>
<script type="text/javascript">
  $(function() {
  	webcam.set_api_url('{% url "mssgs:webcam_upload" %}');
  	webcam.set_swf_url('{% static "mssgs/webcam.swf" %}');
  	$('#webcam').html(webcam.get_html(800, 600));
  });
</script>

{% endblock %}

mssgs/templates/mssgs/message_form_step.html
{% extends "ruik/base.html" %}
{% block head_title %} Новое замечание | {{ block.super }} {% endblock %}

{% block content %}
{{ wizard.form.media }}
{% load static %}
{% load mptt_tags %}

<form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
{% load bootstrap3 %}
{{ wizard.steps.count }}
<table>
{{ wizard.management_form }}
{% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
        {% bootstrap_form form %}
    {% endfor %}
{% else %}
    {% bootstrap_form wizard.form %}
{% endif %}
</table>
{% buttons %}
<div class="btn-group" role="group">
{% if wizard.steps.prev %}
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}" class="btn btn-default">{% bootstrap_icon "fast-backward" %} Первый шаг</button>
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}" class="btn btn-default">{% bootstrap_icon "backward" %} Предыдущий шаг</button>
{% endif %}
{% if wizard.steps.next %}
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.next }}" class="btn btn-default">{% bootstrap_icon "forward" %} Следующий шаг</button>
{% endif %}
</div>

<button type="submit" class="btn btn-primary">
{% bootstrap_icon "ok" %} Отправить
</button>
{% endbuttons %}
</form>


{% endblock %}

mssgs/templates/mssgs/message_list.html
{% extends "ruik/base.html" %}
{% load bootstrap3 %}
{% load static %}


{% block head_title %}Списки | {{ block.super }} {% endblock %}

{% block content %}
<table data-toggle="table"
       id="table"
       data-search="true"
       data-striped="true"
       data-pagination="true"
       data-page-size="20"
       data-page-list=[20,40]
       data-show-pagination-switch="true">
<thead>
<tr>
    <th data-sortable="true" data-sort-name="db_num">Номер обращения</th>
    <th data-field="db_num" data-visible="false"></th>
    <th>Обращение</th>
    <th data-sortable="true" data-sort-name="author" data-field="author">Пользователь</th>
    <th data-sortable="true" data-sort-name="date">Время обращения</th>
    <th data-field="date" data-visible="false"></th>
    <th data-sortable="true" data-sort-name="category" data-field="category">Категория</th>
</tr>
</thead>
<tbody>
{% for message in message_list %}
<tr>
    <td><a href='{% url 'mssgs:detail' message.id %}'>MS{{ message.id }}</a></td>
    <td>{{ message.id }}</td>
    <td>{{ message.message_text|truncatewords:5 }}</td>
    <td>{{ message.author }}</td>
    <td>{{ message.date_create|date:'d.m.y G:i' }}</td>
    <td>{{ message.date_create|date:'U' }}</td>
    <td>{{ message.category.category }}</td>
</tr>
{% endfor %}

</tbody>
</table>


{% endblock %}

mssgs/templates/mssgs/name.html
{% load bootstrap3 %}
<script src="{% bootstrap_jquery_url %}"></script>
{% bootstrap_javascript %}
{% bootstrap_css %}
{% bootstrap_messages %}


<form action="{% url 'mssgs:name' %}" method="post">
    {% csrf_token %}

{% bootstrap_form form %}


  {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Отправить
    </button>
  {% endbuttons %}
</form>

mssgs/templates/mssgs/user_info.html
{% extends "ruik/base.html" %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}
{% load static %}


{% block head_title %}Имя | {{ block.super }} {% endblock %}

{% block content %}

  <p>{{ user_info }}</p>

{% endblock %}