grps/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = 'grps'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='groups'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

mssgs/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views
# from .views import MessageWizard

app_name = 'mssgs'
urlpatterns = [
    url(r'^message$', views.MessageView.as_view(), name='message'),
    # url(r'^messages$', views.IndexView.as_view(), name='messages'),
    url(r'^messages$', views.MessageList.as_view(), name='messages'),
    url(r'^user_info$', views.user_info, name='user_info'),
    url(r'^msg/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^new_message$', MessageWizard.as_view(MessageWizard.form_list),
    # name='new_message'),
    url(r'^(?P<group>[0-9]+)/new_message$',
        views.MessageView.as_view(),
        name='new_message'),
    url(r'^webcam_upload$', views.webcam_upload, name='webcam_upload'),
]

grps/models.py
from django.db import models
from datetime import datetime
# from django.contrib.auth.models import User


class GroupType(models.Model):
    group_type = models.CharField(max_length=250, verbose_name='Тип объекта')

    def __str__(self):
        return self.group_type

    class Meta:
        verbose_name = 'Тип объекта'
        verbose_name_plural = 'Типы объектов'

class Group(models.Model):
    group_name      = models.CharField('Название группы', max_length=250)
    date_create     = models.DateTimeField('Дата создания', auto_now_add=True)
    date_updated    = models.DateTimeField('Дата редактирования', auto_now=True)
    group_type      = models.ForeignKey(GroupType, null=True, blank=True, verbose_name='Тип группы', related_name='groups')
    category_set    = models.ForeignKey('mssgs.CategoriesSet', null=True, blank=True, verbose_name='Набор категорий обращений', related_name='groups')
    date_end        = models.DateField('Срок действия группы', null=True, blank=True)
    glyphicon_name  = models.CharField('Название иконки', max_length=50, default='glyphicon-check')
    glyphicon_color  = models.CharField('Цвет иконки', max_length=50, default='black')

    def __str__(self):
        return self.group_name

    class Meta:
        ordering = ['group_name']
        verbose_name = 'Объект'
        verbose_name_plural = 'Объекты'

# class WorkGroup(models.Model):
#     name = models.ManyToManyField(User)

grps/views.py
from django.views.generic import ListView, DetailView
from django.contrib import messages

# from django_tables2 import SingleTableMixin

# from .tables import MessageTable
from .models import Group

class IndexView(ListView):
    context_object_name = 'latest_groups_list'

    def get_queryset(self):
        return Group.objects.all()

class DetailView(DetailView):
    model = Group
    context_object_name = 'group'

grps/templates/grps/group_detail.html
{% extends "ruik/base.html" %}
{% load querystring from django_tables2 %}
{% load bootstrap3 %}
{% block head_title %} Детали | {{ block.super }} {% endblock %}
{% block content %}

<div class="page-header"><h3>{{ group.group_name }}</h3></div>

{% if group.messages.all %}
{% include "grps/message_table.html" %}
{% endif %}

{% endblock %}

grps/templates/grps/group_list.html
{% extends "ruik/base.html" %}

{% block head_title %}Списки | {{ block.super }} {% endblock %}

{% block content %}
<!--
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-4">
            <div class="panel panel-default">

                <div class="panel-heading">Отображение групп</div>

                <ul class="list-group">
                    <li class="list-group-item">
                        Активные / Все
                        <div class="material-switch pull-right">
                            <input id="someSwitchOptionDefault" name="someSwitchOption001" type="checkbox" class="check_thumbs" />
                            <label for="someSwitchOptionDefault" class="label-default"></label>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div> -->


{% if latest_groups_list %}
<div class="row">
    {% for group in latest_groups_list %}
    {% now 'U' as current_date %}
      <div class="col-sm-6 col-md-4
        {% if group.date_end %}{% if group.date_end|date:'U' < current_date %}
           nonactive_group
        {% endif %}{% endif %}">
        <div class="thumbnail text-center">
          <div style="font-size:3em;margin-top:1em;color:{{group.glyphicon_color}}" class="glyphicon {{group.glyphicon_name}}"></div>
          <div class="caption text-left">
            <div class="thumbs-group-name" style="margin-bottom:1em;">
              <h3>{{ group.group_name }}</h3>
              <p>
                {% if group.date_end is None or group.date_end|date:'U' > current_date %}
                <a href="{% url 'mssgs:new_message' group.id %}" class="btn btn-primary" role="button">Направить обращение</a>
                {% endif %}
                <a href="{% url 'grps:detail' group.id %}" class="btn btn-default" role="button">Все обращения</a>
              </p>
          <div>
            Всего обращений: {{ group.messages.count }}
            {% if group.date_end %}
              <br />Временная группа (до {{ group.date_end|date:'d.m.y' }})
            {% endif %}
          </div>

            </div>

          </div>
        </div>

      </div>

    {% endfor %}
    </div>
{% else %}
    <p>Нет групп.</p>
{% endif %}
</div>
{% endblock %}

grps/templates/grps/message_table.html
<table data-toggle="table"
       id="table"
       data-search="true"
       data-striped="true"
       data-pagination="true"
       data-page-size="20"
       data-page-list=[20,40]
       data-show-pagination-switch="true">
<thead>
<tr>
    <th data-field="status" data-sortable="true" data-sort-name="status">Статус</th>
    <th data-sortable="true" data-sort-name="db_num">Номер обращения</th>
    <th data-field="db_num" data-visible="false"></th>
    <th>Обращение</th>
    <th data-sortable="true" data-sort-name="author" data-field="author">Пользователь</th>
    <th data-sortable="true" data-sort-name="date">Время обращения</th>
    <th data-field="date" data-visible="false"></th>
    <th data-sortable="true" data-sort-name="category" data-field="category">Категория</th>
    <th data-field="ingeneer" data-sortable="true" data-sort-name="ingeneer">Исполнитель</th>
    {% for member in request.user.profile.memeber_person.all %}
      {% if member.group.messages_group == group %}
        <th></th>
      {% endif %}
    {% endfor %}
</tr>
</thead>
<tbody>
{% for message in group.messages.all %}
<tr>
    <td>
      {% if message in massage.status_logs.all %}
        Свой статус
      {% else %}
        Еще не принят в работу c {{ message.date_create|date:"H:i d.m.y" }}
      {% endif %}
    </td>
    <td><a href='{% url 'mssgs:detail' message.id %}'>MS{{ message.id }}</a></td>
    <td>{{ message.id }}</td>
    <td><div title='{{ message.message_text }}'>{{ message.message_text|truncatewords:5 }}</div></td>
    <td>{{ message.author }}</td>
    <td>{{ message.date_create|date:'d.m.y G:i' }}</td>
    <td>{{ message.date_create|date:'U' }}</td>
    <td>{{ message.category.category }}</td>
    <td>{{group}}</td>
      {% for member in request.user.profile.memeber_person.all %}
        {% if member.group.messages_group == group %}
        <td>
            <button type="button" class="btn btn-info" id="to_work_button" data-id={{message.id}}>В работу</button>
        </td>
        {% endif %}
      {% endfor %}
</tr>
{% endfor %}

</tbody>
</table>